# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install python3-dev
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y libpq-dev build-essential

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8080 to allow external connections
EXPOSE 8080

# Define the command to run your application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]
